# trial.yaml

## Where the samples will be written
save_data: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/inner/onmt/example
## Where the vocab(s) will be written
src_vocab: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/inner/onmt/run/example.vocab.src
tgt_vocab: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/inner/onmt/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/cleaned/neural/train.src
        path_tgt: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/cleaned/neural/train.tgt
    valid:
        path_src: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/cleaned/neural/dev_large.src
        path_tgt: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/cleaned/neural/dev_large.tgt

# Train on a single GPU
world_size: 1
#gpu_ranks: [0]
gpu_ranks: [0]


# Where to save the checkpoints
save_model: /storage/brno2/home/souradat/rp-sourada/czech-automatic-inflection/data/inner/onmt/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500
